language: php
php:
- 5.4

dist: trusty
sudo: true

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE opencart;'
  - mysql -u root opencart < opencart.sql
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs
  - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - if [ "$CHECKS" = "yes" ]; then travis_retry composer install-devtools; fi;

cache:
    directories:
        - $HOME/.composer/cache


addons:
  sonarqube:
    organization: "testingucu2017-github"
    token:
      secure: "3a62d805f9521d93899e87be247d253c1fcb3107"
  sauce_connect:
    username: "testingucu.2017"
    access_key: "822c92b4-028e-4448-9507-0f13c1a1d720"

before_script:
  - npm install -g http-server
  - npm install -g pa11y
  - npm install -g pa11y-reporter-ci
  - php -S 127.0.0.1:8765 -t upload &
  - mkdir -p build/logs
  - touch build/logs/clover.xml
  
script:
  - nvm install stable | nvm alias default stable | nvm use stable
  - jdk_switcher use oraclejdk8
  - find admin catalog tests -name *.php | xargs -n 1 -P4 php -l
  - phpunit -c tests/phpunit/phpunit.xml # Estos test no corresponden.
  - phpunit --coverage-clover build/logs/clover.xml
  - sonar-scanner
  - php vendor/codeception/codeception/codecept run api
  - cd vaddy-master
  - nohup http-server -p 8080 >/dev/null 2>&1 & # seguridad
  - cd ..
  - cd pa11y-master
  - pa11y --threshold 40 open-cart.azurewebsites.net -s WCAG2AA
  - cd ..
  - mvn -f tests/ui-functional/pom.xml test
  - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - rm ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - if [ "$CHECKS" = "yes" ]; then composer sca; fi;
  
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  
# Las credenciales fueron agregadas directamente en Travis CI -> Settings
deploy:
  provider: azure_web_apps
  username: "$open-cart"
  password: "b0v22TwzoPtv7ESsnfyT74xoFZZjPawpRbsuZ9kfd4jGBeaLE4q2wXT7xoXH"
  site: "open-cart"

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - TestingUcu2017@gmail.com
    on_success: never  # default: change
    on_failure: always # default: always
