language: php
php:
  - 5.5

dist: trusty
sudo: true

services:
  - mysql

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - TestingUcu2017@gmail.com
    on_success: never  # default: change
    on_failure: always # default: always

addons:
  sonarqube:
    organization: "testingucu2017-github"
    token:
      secure: "3a62d805f9521d93899e87be247d253c1fcb3107"
  code_climate:
      repo_token: "011ad7d37cd7b5219b42a12d07fba180c1e7da66"
  apt:
    packages:
     - ncftp
     - python 
     - default-jre-headless 
     - python-tk 
     - python-pip 
     - python-dev 
     - \libxml2-dev
     - libxslt-dev 
     - zlib1g-dev
     - libwww-perl

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs
  - sudo pip install -q bzt
  - sudo pip install --upgrade six
  #- sudo apt-get install libwww-perl

install:
  - composer install
  - npm install --save-dev eslint
  - mkdir -p build/logs
  - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0
  #- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - if [ "$CHECKS" = "yes" ]; then travis_retry composer install-devtools; fi;

before_script:
  - chmod +x upload-ftp.sh
  - bash upload-ftp.sh
  - npm install -g http-server
  - npm install -g pa11y
  - npm install -g pa11y-reporter-ci
  - mkdir -p build/logs
  - touch build/logs/clover.xml
  - cat build/logs/clover.xml
  - mkdir -p build/logs

script:
  - nvm install stable | nvm alias default stable | nvm use stable
  - find admin catalog tests -name *.php | xargs -n 1 -P4 php -l
#  - phpunit -c tests/phpunit/opencart/OpenCartTest.php
# - phpunit --coverage-clover build/logs/clover.xml
# - composer require codeclimate/php-test-reporter:dev-master
# - phpunit --coverage-clover build/logs/clover.xml
  - cd php-gtmetrix
  - POST /api/0.1/test
  - curl --user santi4707@hotmail.com:6b8b92fdedae63dbec1a9e179baa8137 --form url=http://open-cart.azurewebsites.net/ "https://gtmetrix.com/api/0.1/test"
  - GET /api/0.1/test/{test_id}
  - cd ..
  - sonar-scanner
  - vendor/codeception/codeception/codecept run api
  - cd vaddy-master
  - nohup http-server -p 8080 >/dev/null 2>&1 & # seguridad
  - cd ..
  - cd pa11y-master
  - pa11y --ignore "warning;notice" --threshold 40 open-cart.azurewebsites.net -s WCAG2AA
  - cd ..
  - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - rm ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - if [ "$CHECKS" = "yes" ]; then composer sca; fi;
  - jdk_switcher use oraclejdk8
  - mvn -q -f tests/ui-functional/pom.xml test
  - sudo bzt prueba-1hilo.yml
  - sudo bzt prueba-10hilos.yml


after_success:
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - vendor/bin/test-reporter
  - sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then php vendor/bin/coveralls -v; fi;

after_script:
  - bin/coveralls -v --exclude-no-stmt
  - npm install -g codeclimate-test-reporter
 # - codeclimate-test-reporter < coverage/lcov.info
  - codeclimate-test-reporter < coverage/clover.xml
  - php vendor/bin/coveralls -v
