language: php
php:
- 5.4
- hhvm

services:
  - mysql

sudo: false

install:
- travis_retry composer install --no-interaction

addons:
  sonarqube:
    organization: "testingucu2017-github"
    token:
      secure: "3a62d805f9521d93899e87be247d253c1fcb3107"

script:
- find admin catalog tests -name *.php | xargs -n 1 -P4 php -l
- phpunit -c tests/phpunit/phpunit.xml
- sonar-scanner
- php vendor/codeception/codeception/codecept run api



notifications:
  slack:
    on_success: always
  email:
    recipients:
      - TestingUcu2017@gmail.com      
    on_success: never  # default: change
    on_failure: always # default: always





